# numpy
고성능 과학계산 컴퓨팅과 데이터 분석에 필요한 기본 패키지

In [2]:
import numpy as np

데이터 분석 시 missing value로 사용하는 NaN 값이 이 패키지에 있음

In [5]:
np.nan

nan

### arange를 활용하여 리스트 만들기

In [8]:
np.arange(5.)

array([ 0.,  1.,  2.,  3.,  4.])

In [3]:
np.arange(5)

array([0, 1, 2, 3, 4])

### reshape함수로 matrix 만들기
reshape((행수,열수))

In [5]:
matrix1 = np.arange(15).reshape((5,3))
matrix1

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [6]:
matrix2 = np.arange(15).reshape((3,5))
matrix2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])